version: '2.1'

services:
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Channel:1:1,Conversation:1:1,Subscriber:1:1,Message:1:1"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

